// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giqjidirvkjllbbslykc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpcWppZGlydmtqbGxiYnNseWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjY5MTYsImV4cCI6MjA2NTE0MjkxNn0.bJ4Jp8GEq076Rsz_ZpewWQ3Q9S1W7fDK4LTKX3q586M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);